### ISSUE TITLE
Gives errors from louk-loader

### ISSUE THREAD

**Issue by pearofducks** [louk-lang/louk-intro#1]
Against macOS 10.14.0, node 10.11.0, and npm 6.4.1:

I did `npm i` then `npm run build` and got:

```
Module build failed (from ./node_modules/louk-loader/index.js):
TypeError: Cannot set property 'position' of undefined
    at closingTag (/Users/pear/Movies/louk-intro/node_modules/louk/dist/element-processor.js:120:22)
    at Object.assignMatches (/Users/pear/Movies/louk-intro/node_modules/louk/dist/element-processor.js:86:36)
    at Object.processSections (/Users/pear/Movies/louk-intro/node_modules/louk/dist/section-processor.js:98:45)
    at Object.parse (/Users/pear/Movies/louk-intro/node_modules/louk/dist/parser.js:9:37)
    at module.exports (/Users/pear/Movies/louk-intro/node_modules/louk/dist/index.js:5:19)
    at Object.module.exports (/Users/pear/Movies/louk-intro/node_modules/louk-loader/index.js:6:12)

 @ ./src/main.js 2:0-28 7:17-20
 @ multi ./src/main.js
```

(yes I use `Movies` as a dev dir) 🙈

**Comment by agorischek** [comment]
Hi there! Thanks a bunch for reporting this and apologies for the trouble. I'm investigating now.

**Comment by agorischek** [comment]
I rolled back the breaking change and am investigating root cause. If you run `npm install` again it should take you back to Louk `0.7.5`.

**Comment by agorischek** [comment]
Hi @pearofducks, thanks again for reporting! The core Louk library has been updated to handle this case (including tests), and `louk-intro` now consumes the updated version. Pull the latest version of this repo, `npm install`, and you should be good to go. Let me know if you run into any other issues!
